
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b my-4 mx-2 mb-2 items-center py-2">
          <div className="flex justify-around items-center gap-2 ">
            <div className="underline decoration-1 decoration-gray-400 px-1.5 text-center">
              <button className="flex items-center"><img src="/person.svg" alt="globus" className="w-10 h-10" />is logged In</button>
            </div>


            <span>Student Across Borders</span>
          </div>
        </header>





        {children}</body>
    </html >
  );
}